##
# From scripts to aliases
# Some functions need special name as they may conflict with host binaries that could have same name
# Like help can be host cmd so we need to alias help with mt_help
##

## Typical help menu
alias help='mt_help'
alias setup_android='ndk_health_check'
alias mvm_meson='mvm_meson'
alias mvm_cmake='mvm_cmake'
alias mvm_configure='mvm_configure'
